language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
install:
  - "pip install -U pip wheel setuptools"
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script: "python setup.py nosetests && flake8 attrdict tests"
after_success:
  - coveralls
